name: SageMaker Pipelines Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan-sagemaker-pipelines:
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit
    with:
      environment: "sagemaker-pipelines-staging"
      terraform-environment: staging
      terraform-working-directory: "sagemaker-pipelines/terraform/staging"
      aws-environment: staging
      project: ml
      aws-role-name: mlops-github

  apply-sagemaker-pipelines:
    uses: ./.github/workflows/terraform-deploy.yml
    secrets: inherit
    needs: plan-sagemaker-pipelines
    if: needs.plan-sagemaker-pipelines.result == 'success'
    with:
      environment: "sagemaker-pipelines-staging"
      terraform-environment: staging
      terraform-working-directory: "sagemaker-pipelines/terraform/staging"
      aws-environment: staging
      project: ml
      aws-role-name: mlops-github